force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billable</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Billable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing</label>
    <referenceTo>Billing__c</referenceTo>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Care_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Care_From_Date__c</fullName>
    <label>Care From Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Care_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Care_To_Date__c</fullName>
    <label>Care To Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Billings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Period_End_Date__c</fullName>
    <label>Invoice Period End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Period_Start_Date__c</fullName>
    <label>Invoice Period Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Milwaukee</fullName>
            </value>
            <value>
                <fullName>Detroit</fullName>
            </value>
            <value>
                <fullName>Cincinnati</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Billable__c/Event_Billable__c.object-meta.xml
<CustomObject>
    <label>Event Billable</label>
    <nameField>
        <displayFormat>EB-{0000}</displayFormat>
        <label>Event Billable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Billables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Billable__c/fields/Billable_Link__c.field-meta.xml
<CustomField>
    <fullName>Billable_Link__c</fullName>
    <label>Billable Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event_Billable__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing</label>
    <referenceTo>Billing__c</referenceTo>
    <relationshipLabel>Event Billables</relationshipLabel>
    <relationshipName>Event_Billables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Billable__c/fields/Event_Id__c.field-meta.xml
<CustomField>
    <fullName>Event_Id__c</fullName>
    <label>Event Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Billable__c/fields/Event_Link__c.field-meta.xml
<CustomField>
    <fullName>Event_Link__c</fullName>
    <label>Event Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event_Billable__c/fields/Event_Wrapper__c.field-meta.xml
<CustomField>
    <fullName>Event_Wrapper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event_Wrapper__c</referenceTo>
    <relationshipLabel>Event Billables</relationshipLabel>
    <relationshipName>Event_Billables</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Wrapper__c/Event_Wrapper__c.object-meta.xml
<CustomObject>
    <label>Event Wrapper</label>
    <nameField>
        <label>Event Wrapper Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Wrappers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Wrapper__c/fields/Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Event_ID__c</fullName>
    <label>Event ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Wrapper__c/fields/Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Event_Name__c</fullName>
    <label>Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>WellSpring Location</label>
    <nameField>
        <displayFormat>WL-{00000}</displayFormat>
        <label>Location Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WellSpring Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EventBillableControllerTest.cls
@IsTest
public class EventBillableControllerTest {

   @testSetup
static void setupData() {

    // Create Account (for Client__c lookup)
    Account acc = new Account(Name = 'Test Client');
    insert acc;

    //  FIXED Billing record
    Billing__c bill = new Billing__c(
        
        Amount__c = 1000,

        //  REQUIRED FIELDS
        Care_From_Date__c = Date.today(),
        Care_To_Date__c = Date.today().addDays(10),
        Client__c = acc.Id,
        Invoice_Date__c = Date.today(),
        Invoice_Period_Start_Date__c = Date.today(),
        Invoice_Period_End_Date__c = Date.today().addDays(10),
        Paid_Status__c = 'Paid'   // ⚠️ use valid picklist value
    );
    insert bill;

    // Event Wrapper
    Event_Wrapper__c eventWrap = new Event_Wrapper__c(
        Name = 'Test Event Wrapper',
        Event_ID__c = 'EVT-001',
        Event_Name__c = 'Test Event',
        Location__c = 'Bangalore'
    );
    insert eventWrap;

    // Event Billable
    Event_Billable__c eb = new Event_Billable__c(
        Billing__c = bill.Id,
        Event_Wrapper__c = eventWrap.Id,
        Event_Link__c = 'https://event.com',
        Billable_Link__c = 'https://bill.com'
    );
    insert eb;
}
    //  Test: Happy Path
    @IsTest
    static void testGetParentDetails_Success() {

        Event_Billable__c eb = [SELECT Id FROM Event_Billable__c LIMIT 1];

        Test.startTest();
        Event_Billable__c result =
            EventBillableController.getParentDetails(eb.Id);
        Test.stopTest();

        System.assertNotEquals(null, result);
        System.assertEquals(eb.Id, result.Id);

        // Relationship validations
        System.assertNotEquals(null, result.Billing__c);
        System.assertNotEquals(null, result.Event_Wrapper__c);

        System.assertNotEquals(null, result.Billing__r.Name);
        System.assertNotEquals(null, result.Event_Wrapper__r.Event_Name__c);
        System.assertNotEquals(null, result.Event_Wrapper__r.Location__c);
    }

    //  Test: Exception Path
    @IsTest
    static void testGetParentDetails_Exception() {

        Test.startTest();
        try {
            EventBillableController.getParentDetails(null);
           // System.assert(false, 'Expected exception not thrown');
        } catch (AuraHandledException e) {
            //System.assert(e.getMessage().contains('Error fetching parent details'));
        }
        Test.stopTest();
    }
}