force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billable</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Billable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing</label>
    <referenceTo>Billing__c</referenceTo>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Care_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Care_From_Date__c</fullName>
    <label>Care From Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Care_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Care_To_Date__c</fullName>
    <label>Care To Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Billings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Event_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date_Time__c</fullName>
    <label>Event End Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Event_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date_Time__c</fullName>
    <label>Event Start Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Period_End_Date__c</fullName>
    <label>Invoice Period End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Period_Start_Date__c</fullName>
    <label>Invoice Period Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Is_Synced__c.field-meta.xml
<CustomField>
    <fullName>Is_Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BillingGroupIterableTest.cls
@IsTest
private class BillingGroupIterableTest {

    @IsTest
    static void testBillingGroupIterator() {
        Date fromDate = Date.today();
        Date toDate = Date.today().addDays(3);

        // Create Test Account (Client)
        Account acc = new Account(
            Name = 'Test Client'
        );
        insert acc;

        // Create Billing Records
        List<Billing__c> billings = new List<Billing__c>();

        // Group 1 -> Same Client + Same Location
        billings.add(new Billing__c(
            Client__c = acc.Id,
           Is_Synced__c = false,
            Care_From_Date__c = fromDate,
            Care_To_Date__c = toDate,
            Invoice_Date__c = Date.today(),
            Invoice_Period_Start_Date__c = fromDate,
            Invoice_Period_End_Date__c = toDate,
            Paid_Status__c = 'Paid',
            Amount__c = 100,
            Event_End_Date_Time__c = Datetime.newInstance(2026, 7, 8, 5, 0, 0),
            Event_Start_Date_Time__c = Datetime.newInstance(2026, 7, 9, 5, 0, 0)
        ));

        billings.add(new Billing__c(
            Client__c = acc.Id,
           Is_Synced__c = false,
            Care_From_Date__c = fromDate,
            Care_To_Date__c = toDate,
            Invoice_Date__c = Date.today(),
            Invoice_Period_Start_Date__c = fromDate,
            Invoice_Period_End_Date__c = toDate,
            Paid_Status__c = 'Paid',
            Amount__c = 100,
            Event_End_Date_Time__c = Datetime.newInstance(2026, 7, 8, 5, 0, 0),
            Event_Start_Date_Time__c = Datetime.newInstance(2026, 7, 9, 5, 0, 0)
        ));

        // Group 2
        billings.add(new Billing__c(
            Client__c = acc.Id,
            Is_Synced__c = false,
            Care_From_Date__c = fromDate,
            Care_To_Date__c = toDate,
            Invoice_Date__c = Date.today(),
            Invoice_Period_Start_Date__c = fromDate,
            Invoice_Period_End_Date__c = toDate,
            Paid_Status__c = 'Paid',
            Amount__c = 100,
            Event_End_Date_Time__c = Datetime.newInstance(2026, 7, 8, 5, 0, 0),
            Event_Start_Date_Time__c = Datetime.newInstance(2026, 7, 9, 5, 0, 0)
        ));

        insert billings;

        Test.startTest();

        BillingGroupIterable iterable = new BillingGroupIterable(billings);

        Iterator<List<Billing__c>> iterator = iterable.iterator();

        Integer groupCount = 0;

        while(iterator.hasNext()){

            List<Billing__c> newgroup = iterator.next();

            System.assertNotEquals(null, newgroup);
            System.assert(newgroup.size() > 0);

            groupCount++;

            if(groupCount == 1){
                
            }

            if(groupCount == 2){
                System.assertEquals(1, newgroup.size(),
                    'Second group should contain 1 record.');
            }
        }

        Test.stopTest();

        
    }

    @IsTest
    static void testIteratorNoSuchElementException() {
        Date fromDate = Date.today();
        Date toDate = Date.today().addDays(3);

        Account acc = new Account(
            Name = 'Client 2'
        );
        insert acc;

        Billing__c billing = new Billing__c(
            Client__c = acc.Id,
           	Is_Synced__c = false,
            Care_From_Date__c = fromDate,
            Care_To_Date__c = toDate,
            Invoice_Date__c = Date.today(),
            Invoice_Period_Start_Date__c = fromDate,
            Invoice_Period_End_Date__c = toDate,
            Paid_Status__c = 'Paid',
            Amount__c = 100,
            Event_End_Date_Time__c = Datetime.newInstance(2026, 7, 8, 5, 0, 0),
            Event_Start_Date_Time__c = Datetime.newInstance(2026, 7, 9, 5, 0, 0)
        );

        insert billing;

        BillingGroupIterable iterable =
            new BillingGroupIterable(
                new List<Billing__c>{ billing }
            );

        Iterator<List<Billing__c>> iterator =
            iterable.iterator();

        // Consume the only group
        System.assert(iterator.hasNext());
        iterator.next();

        System.assertEquals(false, iterator.hasNext());

        Boolean exceptionThrown = false;

        try{
            iterator.next();
        }
        catch(NoSuchElementException ex){
            exceptionThrown = true;
            System.assert(
                ex.getMessage().contains('No more billing groups')
            );
        }

        System.assertEquals(
            true,
            exceptionThrown,
            'Expected NoSuchElementException to be thrown.'
        );
    }

    @IsTest
    static void testEmptyBillingList() {

        BillingGroupIterable iterable =
            new BillingGroupIterable(
                new List<Billing__c>()
            );

        Iterator<List<Billing__c>> iterator =
            iterable.iterator();

        System.assertEquals(
            false,
            iterator.hasNext()
        );
    }
}