force-app/main/default/objects/AllergyIntolerance/fields/Allergies__c.field-meta.xml
<CustomField>
    <fullName>Allergies__c</fullName>
    <label>Allergies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACE Inhibitors</fullName>
            </value>
            <value>
                <fullName>Aciphex</fullName>
            </value>
            <value>
                <fullName>Actonel</fullName>
            </value>
            <value>
                <fullName>Actos</fullName>
            </value>
            <value>
                <fullName>Adhesive Tape</fullName>
            </value>
            <value>
                <fullName>Albuterol</fullName>
            </value>
            <value>
                <fullName>Allegra</fullName>
            </value>
            <value>
                <fullName>Allopurinol</fullName>
            </value>
            <value>
                <fullName>Almonds</fullName>
            </value>
            <value>
                <fullName>Amantadine</fullName>
            </value>
            <value>
                <fullName>Amides</fullName>
            </value>
            <value>
                <fullName>Amiodarone</fullName>
            </value>
            <value>
                <fullName>Amoxicillin</fullName>
            </value>
            <value>
                <fullName>Ampicillin</fullName>
            </value>
            <value>
                <fullName>Anectine</fullName>
            </value>
            <value>
                <fullName>Antiemtics</fullName>
            </value>
            <value>
                <fullName>Antihistamines</fullName>
            </value>
            <value>
                <fullName>Aricept</fullName>
            </value>
            <value>
                <fullName>Aspartame</fullName>
            </value>
            <value>
                <fullName>Aspirin (ASA or Salicylates)</fullName>
            </value>
            <value>
                <fullName>Atenolol</fullName>
            </value>
            <value>
                <fullName>Augmentin</fullName>
            </value>
            <value>
                <fullName>Bacitracin</fullName>
            </value>
            <value>
                <fullName>Bactrim</fullName>
            </value>
            <value>
                <fullName>Bananas</fullName>
            </value>
            <value>
                <fullName>Barbituates</fullName>
            </value>
            <value>
                <fullName>Bee Stings</fullName>
            </value>
            <value>
                <fullName>Benadryl</fullName>
            </value>
            <value>
                <fullName>Beta-Adrenergic Blockers</fullName>
            </value>
            <value>
                <fullName>Bisphosphonates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AllergyIntolerance/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Initial_Assessment__c</referenceTo>
    <relationshipLabel>Allergies</relationshipLabel>
    <relationshipName>Allergy_Intolerances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AllergyIntolerance/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Allergy Intolerances</relationshipLabel>
    <relationshipName>Allergy_Intolerances</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HealthCondition/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Assessment</label>
    <referenceTo>Initial_Assessment__c</referenceTo>
    <relationshipLabel>Health Conditions</relationshipLabel>
    <relationshipName>Health_Conditions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HealthCondition/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Health Conditions</relationshipLabel>
    <relationshipName>Health_Conditions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/Initial_Assessment__c.object-meta.xml
<CustomObject>
    <label>Assessment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieved-preprod/objects/Initial_Assessment__c/fields/Allergies__c.field-meta.xml
<CustomField>
    <fullName>Allergies__c</fullName>
    <label>Allergies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACE Inhibitors</fullName>
            </value>
            <value>
                <fullName>Aciphex</fullName>
            </value>
            <value>
                <fullName>Actonel</fullName>
            </value>
            <value>
                <fullName>Actos</fullName>
            </value>
            <value>
                <fullName>Adhesive Tape</fullName>
            </value>
            <value>
                <fullName>Albuterol</fullName>
            </value>
            <value>
                <fullName>Allegra</fullName>
            </value>
            <value>
                <fullName>Allopurinol</fullName>
            </value>
            <value>
                <fullName>Almonds</fullName>
            </value>
            <value>
                <fullName>Amantadine</fullName>
            </value>
            <value>
                <fullName>Amides</fullName>
            </value>
            <value>
                <fullName>Amiodarone</fullName>
            </value>
            <value>
                <fullName>Amoxicillin</fullName>
            </value>
            <value>
                <fullName>Ampicillin</fullName>
            </value>
            <value>
                <fullName>Anectine</fullName>
            </value>
            <value>
                <fullName>Antiemtics</fullName>
            </value>
            <value>
                <fullName>Antihistamines</fullName>
            </value>
            <value>
                <fullName>Aricept</fullName>
            </value>
            <value>
                <fullName>Aspartame</fullName>
            </value>
            <value>
                <fullName>Aspirin (ASA or Salicylates)</fullName>
            </value>
            <value>
                <fullName>Atenolol</fullName>
            </value>
            <value>
                <fullName>Augmentin</fullName>
            </value>
            <value>
                <fullName>Bacitracin</fullName>
            </value>
            <value>
                <fullName>Bactrim</fullName>
            </value>
            <value>
                <fullName>Bananas</fullName>
            </value>
            <value>
                <fullName>Barbituates</fullName>
            </value>
            <value>
                <fullName>Bee Stings</fullName>
            </value>
            <value>
                <fullName>Benadryl</fullName>
            </value>
            <value>
                <fullName>Beta-Adrenergic Blockers</fullName>
            </value>
            <value>
                <fullName>Bisphosphonates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

retrieved-preprod/objects/Initial_Assessment__c/fields/Can_client_be_left_alone__c.field-meta.xml
<CustomField>
    <fullName>Can_client_be_left_alone__c</fullName>
    <label>Can client be left alone?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/fields/Chronic_Acute_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Chronic_Acute_Conditions__c</fullName>
    <label>Chronic / Acute Conditions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/fields/Depression__c.field-meta.xml
<CustomField>
    <fullName>Depression__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Depression</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/fields/Diagnosed_Disorders_Medications__c.field-meta.xml
<CustomField>
    <fullName>Diagnosed_Disorders_Medications__c</fullName>
    <label>Diagnosed Disorders / Medications</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

retrieved-preprod/objects/Initial_Assessment__c/fields/Functional_Limitations__c.field-meta.xml
<CustomField>
    <fullName>Functional_Limitations__c</fullName>
    <label>Functional Limitations</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amputation</fullName>
            </value>
            <value>
                <fullName>Bowel/Bladder (Incontinence)</fullName>
            </value>
            <value>
                <fullName>Contracture</fullName>
            </value>
            <value>
                <fullName>Hearing</fullName>
            </value>
            <value>
                <fullName>Paralysis</fullName>
            </value>
            <value>
                <fullName>Endurance</fullName>
            </value>
            <value>
                <fullName>Ambulation</fullName>
            </value>
            <value>
                <fullName>Speech</fullName>
            </value>
            <value>
                <fullName>Legally Blind</fullName>
            </value>
            <value>
                <fullName>Dyspnea with Minimal Exertion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/fields/Hearing__c.field-meta.xml
<CustomField>
    <fullName>Hearing__c</fullName>
    <label>Hearing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
            <value>
                <fullName>Deaf</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/fields/Hearing_Aid__c.field-meta.xml
<CustomField>
    <fullName>Hearing_Aid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hearing Aid</label>
    <type>Checkbox</type>
</CustomField>

retrieved-preprod/objects/Initial_Assessment__c/fields/Lethargy__c.field-meta.xml
<CustomField>
    <fullName>Lethargy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lethargy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/fields/Notes_Allergies__c.field-meta.xml
<CustomField>
    <fullName>Notes_Allergies__c</fullName>
    <label>Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

retrieved-preprod/objects/Initial_Assessment__c/fields/Other_for_Medical_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Other_for_Medical_Conditions__c</fullName>
    <label>Other</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Smoker</fullName>
            </value>
            <value>
                <fullName>Sensitive to Smell</fullName>
            </value>
            <value>
                <fullName>On Oxygen</fullName>
            </value>
            <value>
                <fullName>Colostomy Bag</fullName>
            </value>
            <value>
                <fullName>Feeding Tube</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

retrieved-preprod/objects/Initial_Assessment__c/fields/Past_Current_Substance_Abuse__c.field-meta.xml
<CustomField>
    <fullName>Past_Current_Substance_Abuse__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Past/Current Substance Abuse</label>
    <type>Checkbox</type>
</CustomField>

retrieved-preprod/objects/Initial_Assessment__c/fields/Prospect__c.field-meta.xml
<CustomField>
    <fullName>Prospect__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Prospect</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assessments</relationshipLabel>
    <relationshipName>Initial_Assessments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/fields/Speech__c.field-meta.xml
<CustomField>
    <fullName>Speech__c</fullName>
    <label>Speech</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/fields/Swallowing__c.field-meta.xml
<CustomField>
    <fullName>Swallowing__c</fullName>
    <label>Swallowing</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/fields/Vision__c.field-meta.xml
<CustomField>
    <fullName>Vision__c</fullName>
    <label>Vision</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Good</fullName>
            </value>
            <value>
                <fullName>Poor</fullName>
            </value>
            <value>
                <fullName>Blind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Initial_Assessment__c/fields/Wanderer__c.field-meta.xml
<CustomField>
    <fullName>Wanderer__c</fullName>
    <label>Wanderer?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssessmentTriggerHandler.cls
/*
----------------------------------------------------------------------------
Author         : Narayana Raja Bommidi
Class Name     : AssessmentTriggerHandler
CreatedOn      : 05-05-2026
LastModifiedOn : 21-05-2026
LastModifiedBy : Narayana Raja Bommidi
Description    : This handler class is used to synchronize AllergyIntolerance
                 and HealthCondition records with Initial Assessment data.
                 It manages insert, update, and delete operations based on
                 assessment field changes and maintains related patient
                 health and allergy information.
----------------------------------------------------------------------------
*/
public class AssessmentTriggerHandler {
    private static Boolean isRunning = false;

    public static void deleteChildRecords( List<Initial_Assessment__c> assessments ) {
        Set<Id> assessmentIds = new Set<Id>();

        for (Initial_Assessment__c ass : assessments) {
            assessmentIds.add(ass.Id);
        }

        List<AllergyIntolerance> allergies = [
            SELECT Id
            FROM AllergyIntolerance
            WHERE Assessment__c IN :assessmentIds
        ];

        if (!allergies.isEmpty()) {
            delete allergies;
        }

        List<HealthCondition> healthConditions = [
            SELECT Id
            FROM HealthCondition
            WHERE Assessment__c IN :assessmentIds
        ];

        if (!healthConditions.isEmpty()) {
            delete healthConditions;
        }
    }
    
    public static void handleAllergySync(
        List<Initial_Assessment__c> newList,
        Map<Id, Initial_Assessment__c> oldMap
    ) {

        Set<Id> assessmentIds =
            new Map<Id, Initial_Assessment__c>(
                newList
            ).keySet();

        Map<Id, AllergyIntolerance> existingMap =
            new Map<Id, AllergyIntolerance>();

        for (AllergyIntolerance al : [
            SELECT Id, Assessment__c
            FROM AllergyIntolerance
            WHERE Assessment__c IN :assessmentIds
        ]) {

            existingMap.put(
                al.Assessment__c,
                al
            );
        }

        List<AllergyIntolerance> toInsert =
            new List<AllergyIntolerance>();

        List<AllergyIntolerance> toUpdate =
            new List<AllergyIntolerance>();

        List<AllergyIntolerance> toDelete =
            new List<AllergyIntolerance>();

        for (Initial_Assessment__c rec : newList) {

            Initial_Assessment__c oldRec =
                oldMap != null
                ? oldMap.get(rec.Id)
                : null;

            Boolean isChanged =
                oldMap == null ||
                (
                    oldRec != null &&
                    (
                        rec.Allergies__c != oldRec.Allergies__c ||
                        rec.Notes_Allergies__c != oldRec.Notes_Allergies__c
                    )
                );

            Boolean hasValue =
                String.isNotBlank(rec.Allergies__c);

            if (!isChanged) {
                continue;
            }

            // -----------------------------------------------------------------
            // DELETE
            // -----------------------------------------------------------------
            if (!hasValue &&
                existingMap.containsKey(rec.Id)) {

                toDelete.add(
                    existingMap.get(rec.Id)
                );

                continue;
            }

            // -----------------------------------------------------------------
            // INSERT / UPDATE
            // -----------------------------------------------------------------
            if (hasValue) {

                if (existingMap.containsKey(rec.Id)) {

                    AllergyIntolerance existing =
                        existingMap.get(rec.Id);
                    
                    existing.Prospect__c = rec.Prospect__c;

                    mapAllergyFields(
                        existing,
                        rec
                    );

                    toUpdate.add(existing);

                } else {

                    AllergyIntolerance al =
                        new AllergyIntolerance();

                    al.Assessment__c = rec.Id;
                    al.PatientId     = rec.Prospect__c;
                    al.Prospect__c   = rec.Prospect__c;

                    mapAllergyFields(
                        al,
                        rec
                    );

                    toInsert.add(al);
                }
            }
        }

        if (!toInsert.isEmpty()) {
            Database.insert(toInsert, false);
        }

        if (!toUpdate.isEmpty()) {
            Database.update(toUpdate, false);
        }

        if (!toDelete.isEmpty()) {
            Database.delete(toDelete, false);
        }
    }

    // -------------------------------------------------------------------------
    public static void handleHealthConditionSync(
        List<Initial_Assessment__c> newList,
        Map<Id, Initial_Assessment__c> oldMap
    ) {

        Set<Id> assessmentIds =
            new Map<Id, Initial_Assessment__c>(
                newList
            ).keySet();

        Map<Id, HealthCondition> existingMap =
            new Map<Id, HealthCondition>();

        for (HealthCondition hc : [
            SELECT Id, Assessment__c
            FROM HealthCondition
            WHERE Assessment__c IN :assessmentIds
        ]) {

            existingMap.put(
                hc.Assessment__c,
                hc
            );
        }

        List<HealthCondition> toInsert =
            new List<HealthCondition>();

        List<HealthCondition> toUpdate =
            new List<HealthCondition>();

        List<HealthCondition> toDelete =
            new List<HealthCondition>();

        for (Initial_Assessment__c rec : newList) {

            Initial_Assessment__c oldRec =
                oldMap != null
                ? oldMap.get(rec.Id)
                : null;

            Boolean isChanged =
                hasHealthConditionChanged(
                    rec,
                    oldRec,
                    oldMap
                );

            Boolean hasValue =
                hasHealthConditionValues(rec);

            if (!isChanged) {
                continue;
            }

            // -----------------------------------------------------------------
            // DELETE
            // -----------------------------------------------------------------
            if (!hasValue &&
                existingMap.containsKey(rec.Id)) {

                toDelete.add(
                    existingMap.get(rec.Id)
                );

                continue;
            }

            // -----------------------------------------------------------------
            // INSERT / UPDATE
            // -----------------------------------------------------------------
            if (hasValue) {

                if (existingMap.containsKey(rec.Id)) {

                    HealthCondition existing =
                        existingMap.get(rec.Id);
                                        
                    existing.Prospect__c = rec.Prospect__c;

                    mapHealthConditionFields(
                        existing,
                        rec
                    );

                    toUpdate.add(existing);

                } else {

                    HealthCondition hc =
                        new HealthCondition();

                    hc.Assessment__c = rec.Id;
                    hc.PatientId     = rec.Prospect__c;
                    hc.Prospect__c   = rec.Prospect__c;

                    mapHealthConditionFields(
                        hc,
                        rec
                    );

                    toInsert.add(hc);
                }
            }
        }

        if (!toInsert.isEmpty()) {
            Database.insert(toInsert, false);
        }

        if (!toUpdate.isEmpty()) {
            Database.update(toUpdate, false);
        }

        if (!toDelete.isEmpty()) {
            Database.delete(toDelete, false);
        }
    }

    // -------------------------------------------------------------------------
    private static void mapAllergyFields(
        AllergyIntolerance al,
        Initial_Assessment__c rec
    ) {

        al.Allergies__c = rec.Allergies__c;
        al.Notes__c = rec.Notes_Allergies__c;
    }

    // -------------------------------------------------------------------------
    private static void mapHealthConditionFields(
        HealthCondition hc,
        Initial_Assessment__c rec
    ) {

        hc.Chronic_Acute_Conditions__c =
            rec.Chronic_Acute_Conditions__c;

        hc.Hearing__c = rec.Hearing__c;
        hc.Speech__c = rec.Speech__c;
        hc.Hearing_Aid__c = rec.Hearing_Aid__c;
        hc.Vision__c = rec.Vision__c;
        hc.Swallowing__c = rec.Swallowing__c;

        hc.Other_for_Medical_Conditions__c =
            rec.Other_for_Medical_Conditions__c;

        hc.Functional_Limitations__c =
            rec.Functional_Limitations__c;

        hc.Diagnosed_Disorders_Medications__c =
            rec.Diagnosed_Disorders_Medications__c;

        hc.Lethargy__c = rec.Lethargy__c;
        hc.Depression__c = rec.Depression__c;

        hc.Past_Current_Substance_Abuse__c =
            rec.Past_Current_Substance_Abuse__c;

        hc.Can_client_be_left_alone__c =
            rec.Can_client_be_left_alone__c;

        hc.Wanderer__c = rec.Wanderer__c;
        hc.Dementia__c = rec.Dementia__c;
        hc.Symptoms__c = rec.Symptoms__c;
        hc.Triggers__c = rec.Triggers__c;
    }

    // -------------------------------------------------------------------------
    private static Boolean hasHealthConditionChanged(
        Initial_Assessment__c rec,
        Initial_Assessment__c oldRec,
        Map<Id, Initial_Assessment__c> oldMap
    ) {

        return
            oldMap == null ||
            (
                oldRec != null &&
                (
                    rec.Chronic_Acute_Conditions__c != oldRec.Chronic_Acute_Conditions__c ||
                    rec.Hearing__c != oldRec.Hearing__c ||
                    rec.Speech__c != oldRec.Speech__c ||
                    rec.Hearing_Aid__c != oldRec.Hearing_Aid__c ||
                    rec.Vision__c != oldRec.Vision__c ||
                    rec.Swallowing__c != oldRec.Swallowing__c ||
                    rec.Other_for_Medical_Conditions__c != oldRec.Other_for_Medical_Conditions__c ||
                    rec.Functional_Limitations__c != oldRec.Functional_Limitations__c ||
                    rec.Diagnosed_Disorders_Medications__c != oldRec.Diagnosed_Disorders_Medications__c ||
                    rec.Lethargy__c != oldRec.Lethargy__c ||
                    rec.Depression__c != oldRec.Depression__c ||
                    rec.Past_Current_Substance_Abuse__c != oldRec.Past_Current_Substance_Abuse__c ||
                    rec.Can_client_be_left_alone__c != oldRec.Can_client_be_left_alone__c ||
                    rec.Wanderer__c != oldRec.Wanderer__c ||
                    rec.Dementia__c != oldRec.Dementia__c ||
                    rec.Symptoms__c != oldRec.Symptoms__c ||
                    rec.Triggers__c != oldRec.Triggers__c
                )
            );
    }

    // -------------------------------------------------------------------------
    private static Boolean hasHealthConditionValues(
        Initial_Assessment__c rec
    ) {

        return
            String.isNotBlank(rec.Chronic_Acute_Conditions__c) ||
            String.isNotBlank(rec.Hearing__c) ||
            String.isNotBlank(rec.Speech__c) ||
            rec.Hearing_Aid__c ||
            String.isNotBlank(rec.Vision__c) ||
            String.isNotBlank(rec.Swallowing__c) ||
            String.isNotBlank(rec.Other_for_Medical_Conditions__c) ||
            String.isNotBlank(rec.Functional_Limitations__c) ||
            String.isNotBlank(rec.Diagnosed_Disorders_Medications__c) ||
            rec.Lethargy__c ||
            rec.Depression__c ||
            rec.Past_Current_Substance_Abuse__c ||
            String.isNotBlank(rec.Can_client_be_left_alone__c) ||
            String.isNotBlank(rec.Wanderer__c) ||
            String.isNotBlank(rec.Dementia__c) ||
            String.isNotBlank(rec.Symptoms__c) ||
            String.isNotBlank(rec.Triggers__c);
    }
}