force-app/main/default/objects/Account/fields/Location_g__c.field-meta.xml
<CustomField>
    <fullName>Location_g__c</fullName>
    <inlineHelpText>Please ensure the Selected location value spelling is correct.</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WellSky_Location</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/QB_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>QB_Customer_ID__c</fullName>
    <externalId>true</externalId>
    <label>QB Customer ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billable</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Billable Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Invoice Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Billing__c.field-meta.xml
<CustomField>
    <fullName>Billing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing</label>
    <referenceTo>Billing__c</referenceTo>
    <relationshipName>Billings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Care_From_Date__c.field-meta.xml
<CustomField>
    <fullName>Care_From_Date__c</fullName>
    <label>Care From Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Care_To_Date__c.field-meta.xml
<CustomField>
    <fullName>Care_To_Date__c</fullName>
    <label>Care To Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Billings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice_Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Period_End_Date__c</fullName>
    <label>Invoice Period End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Invoice_Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Period_Start_Date__c</fullName>
    <label>Invoice Period Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Is_Synced__c.field-meta.xml
<CustomField>
    <fullName>Is_Synced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Synced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Location_g__c.field-meta.xml
<CustomField>
    <fullName>Location_g__c</fullName>
    <inlineHelpText>Please ensure the Selected location value spelling is correct.</inlineHelpText>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>WellSky_Location</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Paid_Status__c.field-meta.xml
<CustomField>
    <fullName>Paid_Status__c</fullName>
    <label>Paid Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Unpaid</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing__c/fields/QB_Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>QB_Sync_Status__c</fullName>
    <label>QB Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Billing_Line_Item__c/Billing_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Billable Line Item</label>
    <nameField>
        <displayFormat>BL-{0000}</displayFormat>
        <label>Billable Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billable Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Total Billable Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billing_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Billing__c</referenceTo>
    <relationshipName>Billing_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Billing_Line_Item__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billing_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client Billable</fullName>
            </value>
            <value>
                <fullName>Caregiver Billable</fullName>
                <label>Care Manager Pay</label>
            </value>
            <value>
                <fullName>Mileage</fullName>
            </value>
            <value>
                <fullName>Expense/Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/WellSky_Location.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Detroit</fullName>
    </customValue>
    <customValue>
        <fullName>Milwaukee</fullName>
    </customValue>
    <customValue>
        <fullName>Cincinnati</fullName>
    </customValue>
    <customValue>
        <fullName>Madison</fullName>
    </customValue>
    <customValue>
        <fullName>Dallas</fullName>
    </customValue>
    <masterLabel>WellSky Location</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BillingSyncLWCControllerTest.cls
@isTest
private class BillingSyncLWCControllerTest {

   @testSetup
static void createData() {

    Account acc = new Account(
        Name = 'Test Account'
    );
    insert acc;

    Billing__c bill = new Billing__c(
        Client__c = acc.Id,
        Care_From_Date__c = Date.today(),
        Care_To_Date__c = Date.today().addDays(7),
        Invoice_Date__c = Date.today(),
        Invoice_Period_Start_Date__c = Date.today(),
        Invoice_Period_End_Date__c = Date.today().addDays(7),
        Paid_Status__c = 'Unpaid',
        Amount__c=100
    );

    insert bill;
}

   @isTest
static void testSyncSelectedBillings_Success() {

    List<Id> billingIds = new List<Id>();

    for(Billing__c b : [
        SELECT Id
        FROM Billing__c
        LIMIT 1
    ]) {
        billingIds.add(b.Id);
    }

    Test.startTest();

    BillingSyncLWCController.syncSelectedBillings(billingIds);

    Test.stopTest();

    System.assertEquals(1, billingIds.size());
}
    @isTest
    static void testSyncSelectedBillings_EmptyList() {

        Test.startTest();

        try {

            BillingSyncLWCController.syncSelectedBillings(
                new List<Id>()
            );

            System.assert(false,
                'Exception should have been thrown');

        } catch (AuraHandledException ex) {

           // System.assertEquals('Please select at least one record.', ex.getMessage() );
        }

        Test.stopTest();
    }

    @isTest
    static void testSyncSelectedBillings_NullList() {

        Test.startTest();

        try {

            BillingSyncLWCController.syncSelectedBillings(null);

            System.assert(false,
                'Exception should have been thrown');

        } catch (AuraHandledException ex) {

            //System.assertEquals('Please select at least one record.', ex.getMessage() );
        }

        Test.stopTest();
    }
    @isTest
static void testGetBatchStatus() {

    // Test Data
    Account acc = new Account(
        Name = 'Test Account',
        QB_Customer_Id__c = 'QB-CUST'
    );
    insert acc;

    Date d = Date.today();

    Billing__c billing = new Billing__c(
        Client__c = acc.Id,
        Amount__c = 100,
        Care_From_Date__c = d,
        Care_To_Date__c = d,
        Paid_Status__c = 'Unpaid',
        Invoice_Date__c = d,
        Invoice_Period_Start_Date__c = d.toStartOfMonth(),
        Invoice_Period_End_Date__c = d.toStartOfMonth().addMonths(1).addDays(-1),
        Due_Date__c = d.addDays(5),
        Location_g__c = 'Detroit',
        QB_Sync_Status__c = 'Pending',
        Is_Synced__c = false
    );
    insert billing;

    insert new Billing_Line_Item__c(
        Invoice__c = billing.Id,
        Type__c = 'Client Billable',
        Quantity__c = 1,
        Rate__c = 100,
        Amount__c = 100,
        Service_Date__c = Date.today(),
        Description__c = 'Service'
    );

    Test.setMock(HttpCalloutMock.class,
        new UniversalMock());

    Test.startTest();

    Id jobId = BillingSyncLWCController.syncSelectedBillings(
        new List<Id>{ billing.Id }
    );

    String status = BillingSyncLWCController.getBatchStatus(jobId);

    Test.stopTest();

    System.assertNotEquals(null, status);
    System.assert(
        status == 'Queued' ||
        status == 'Preparing' ||
        status == 'Processing' ||
        status == 'Completed',
        'Unexpected Batch Status: ' + status
    );
}
    private class UniversalMock implements HttpCalloutMock {

    public HttpResponse respond(HttpRequest req) {

        HttpResponse res = new HttpResponse();
        String endpoint = req.getEndpoint().toLowerCase();

        if(endpoint.contains('query')){
            res.setStatusCode(200);
            res.setBody('{"QueryResponse":{}}');
            return res;
        }

        if(endpoint.contains('customer/')){
            res.setStatusCode(200);
            res.setBody(
                '{"Customer":{"Id":"QB-CUST","SyncToken":"0"}}'
            );
            return res;
        }

        if(endpoint.contains('customer')){
            res.setStatusCode(200);
            res.setBody(
                '{"Customer":{"Id":"QB-CUST","SyncToken":"0"}}'
            );
            return res;
        }

        if(endpoint.contains('invoice')){
            res.setStatusCode(200);
            res.setBody(
                '{"Invoice":{"Id":"QB-INV","SyncToken":"0","Line":[{"Id":"1"}]}}'
            );
            return res;
        }

        res.setStatusCode(200);
        res.setBody('{}');
        return res;
    }
}
}