force-app/main/default/objects/Data_Sync_Job__c/Data_Sync_Job__c.object-meta.xml
<CustomObject>
    <description>Use to start a push or pull of data to a system.</description>
    <label>Data Sync Job</label>
    <nameField>
        <displayFormat>DSJ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Sync Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Sync_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Abort</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataSyncProcessRecordsPaginationBatch.cls
global class DataSyncProcessRecordsPaginationBatch implements Database.Batchable<sObject>, Database.AllowsCallouts,Database.Stateful{ 
    Private Integer pageCount;
    Private Integer totalPage;
    Private Data_Sync_Job__c pendingChange;
    public DataSyncProcessRecordsPaginationBatch(integer pageCount,Integer totalPage,Data_Sync_Job__c pendingChange) {
        System.debug('Cons pageCount::'+pageCount);
        this.pageCount = pageCount;
        this.totalPage = totalPage;
        this.pendingChange = pendingChange;

}

global Database.QueryLocator start(Database.BatchableContext BC) {
   
    String query = 'SELECT Id FROM Data_Sync_Job__c where Id = \'' + this.pendingChange.Id + '\' order by Id ASC';
    System.debug('query:'+query);
    return Database.getQueryLocator(query);
}

global void execute(Database.BatchableContext BC, List<Data_Sync_Job__c> pendingChangeList) {
   // TODO do rest page callout and map the fields
    System.debug('pageCount::'+this.pageCount);
    System.debug('totalPage::'+this.totalPage);
    this.pageCount = this.pageCount + 1;
}   

global void finish(Database.BatchableContext BC) {
    if(this.totalPage == this.pageCount ){
        //this.pendingChange.Response__c = (DataSyncProcessor.oldResponse)?.getBody()?.left(13172);
        this.pendingChange.Status__c = 'Complete';
        update this.pendingChange;
        return;
    }
    DataSyncProcessRecordsPaginationBatch job = new DataSyncProcessRecordsPaginationBatch(this.pageCount,this.totalPage,this.pendingChange);
    database.executeBatch(job);
}
 }