force-app/main/default/objects/Data_Sync_Job__c/Data_Sync_Job__c.object-meta.xml
<CustomObject>
    <description>Use to start a push or pull of data to a system.</description>
    <label>Data Sync Job</label>
    <nameField>
        <displayFormat>DSJ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Sync Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Sync_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Abort</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataSyncPaginationBatchTest.cls
@IsTest
public class DataSyncPaginationBatchTest {
    @TestSetup
    static void setupData() {
        Data_Sync_Job__c pendingJob = new Data_Sync_Job__c(
            Status__c = 'Pending',
            Response__c = null
        );
        insert pendingJob;
    }

    @IsTest
    static void testBatchProcessMultiplePages() {
        Data_Sync_Job__c pendingJob = [SELECT Id FROM Data_Sync_Job__c LIMIT 1];
        Integer pageCount = 1;
        Integer totalPage = 3;
        DataSyncProcessRecordsPaginationBatch batch = new DataSyncProcessRecordsPaginationBatch(pageCount, totalPage, pendingJob);

        Test.startTest();
        Database.QueryLocator ql = batch.start(null);
        System.assertNotEquals(null, ql);

        List<Data_Sync_Job__c> syncJobList = new List<Data_Sync_Job__c> { pendingJob };
        batch.execute(null, syncJobList);

        batch.finish(null);
        Test.stopTest();
        Data_Sync_Job__c completedJob = [SELECT Status__c FROM Data_Sync_Job__c WHERE Id = :pendingJob.Id];
        System.assertEquals('Complete', completedJob.Status__c, 'The Data_Sync_Job__c status should be marked as Complete after all pages are processed.');
    }  
}