force-app/main/default/objects/Data_Sync_Job__c/Data_Sync_Job__c.object-meta.xml
<CustomObject>
    <description>Use to start a push or pull of data to a system.</description>
    <label>Data Sync Job</label>
    <nameField>
        <displayFormat>DSJ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Sync Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Sync_Job__c/fields/Retry_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Retry_Attempts__c</fullName>
    <label>Retry Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Data_Sync_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Abort</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataSyncQueableTest.cls
@isTest
public class DataSyncQueableTest {
    
    @isTest
    static void testExecuteWithoutContinuation() {
        Data_Sync_Job__c job = new Data_Sync_Job__c();
        job.Status__c = 'Pending';
        job.External_System__c = 'TestSystem';
        job.Retry_Attempts__c = null;

        Test.startTest();
        
        DataSyncQueable queueableJob = new DataSyncQueable(false);
        System.enqueueJob(queueableJob);
        
        Test.stopTest();

    }

    @isTest
    static void testExecuteWithExistingJob() {
        Data_Sync_Job__c existingJob = new Data_Sync_Job__c();
        existingJob.Status__c = 'Retry';
        insert existingJob;

        AsyncApexJob job = new AsyncApexJob();


        Test.startTest();
        
        DataSyncQueable queueableJob = new DataSyncQueable(false);
        System.enqueueJob(queueableJob);
        
        Test.stopTest();

        existingJob = [SELECT Status__c FROM Data_Sync_Job__c WHERE Id = :existingJob.Id];
    }

    @isTest
    static void testExecuteWithError() {
        Data_Sync_Job__c job = new Data_Sync_Job__c();
        job.Status__c = 'Pending';
        job.External_System__c = 'TestSystem';

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorError());
        
        DataSyncQueable queueableJob = new DataSyncQueable(false);
        System.enqueueJob(queueableJob);
        
        Test.stopTest();

    }

    public class MockHttpResponseGeneratorError implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HTTPResponse res = new HTTPResponse();
            res.setStatusCode(500); 
            return res;
        }
    }

}