force-app/main/default/objects/Data_Sync_Job__c/Data_Sync_Job__c.object-meta.xml
<CustomObject>
    <description>Use to start a push or pull of data to a system.</description>
    <label>Data Sync Job</label>
    <nameField>
        <displayFormat>DSJ-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Sync Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Sync_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Abort</fullName>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DataSyncTriggerHandler.cls
public with sharing class DataSyncTriggerHandler {
    public void onAfterInsert(List<Data_Sync_Job__c> newRecords, Map<Id, Data_Sync_Job__c> newRecordsMap) {
        // if any records are inserted with Status__c = 'Pending' then start the DataSyncQueable job.
        boolean startJob = false;
        for (Data_Sync_Job__c newRecord : newRecords) {
            if (newRecord.Status__c == 'Pending') {
                startJob = true;
                break;
            }
        }
        
        if (startJob){
            DataSyncQueable job = new DataSyncQueable(false);
            System.enqueueJob(job);
        }
    }
    public void onAfterUpdate(List<Data_Sync_Job__c> newRecords, List<Data_Sync_Job__c> oldRecords, Map<Id, Data_Sync_Job__c> newRecordsMap, Map<Id, Data_Sync_Job__c> oldRecordsMap) {
        
        // if any records just became 'Pending' then start the DataSyncQueable job.
        boolean startJob = false;
        for (Data_Sync_Job__c newRecord : newRecords) {
            if (newRecord.Status__c == 'Pending') {
                Data_Sync_Job__c oldRecord = oldRecordsMap.get(newRecord.Id);
                if (oldRecord.Status__c != 'Pending') {
                    startJob = true;
                    break;
                }
            }
        }
        if (startJob){
            DataSyncQueable job = new DataSyncQueable(false);
            System.enqueueJob(job);
        }
        
    }
}