force-app/main/default/objects/Contact/fields/Clients_Referred__c.field-meta.xml
<CustomField>
    <fullName>Clients_Referred__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Clients Referred</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lifetime_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Lifetime_Revenue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lifetime Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Prospects_Referred__c.field-meta.xml
<CustomField>
    <fullName>Prospects_Referred__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Prospects Referred</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Records_Updated_On__c.field-meta.xml
<CustomField>
    <fullName>Records_Updated_On__c</fullName>
    <label>Records Updated On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ContactReferralMetricsController.cls
/*
----------------------------------------------------------------------------
Author        : Siva Naga Prasad
Class Name    : ContactReferralMetricsController
CreatedOn     : 21-01-2026
LastModifiedOn: 21-05-2026
LastModifiedBy: Siva Naga Prasad
Description   : This class is used for Contact Referral Metrics component to read the fields values.
----------------------------------------------------------------------------
*/
public with sharing class ContactReferralMetricsController {

    @AuraEnabled(cacheable=true)
    public static Contact getContactMetrics(Id contactId) {
        return [
            SELECT Id,
                   Prospects_Referred__c,
                   Clients_Referred__c,
                   Lifetime_Revenue__c,
                   Records_Updated_On__c
            FROM Contact
            WHERE Id = :contactId
            LIMIT 1
        ];
    }

    @AuraEnabled
    public static void runBatch() {
        Database.executeBatch(new ContactReferralMetricsBatch(), 200);
    }
}